/*
CREATED BY: JORDAN GODWIN
CREATE DATE: 05/12/2023
DESCRIPTION: AGGREGATE FUNCTIONS \ WHAT ARE OUR ALL TIME GLOBAL SALES
*/
SELECT
	SUM(TOTAL) AS 'Total Sales',
	AVG(total) AS 'Average Sales,',
	MAX(total) AS 'Maximum Sale',
	MIN(total) AS  'Minimum Sales',
	COUNT(*) AS 'Sales count'

FROM
	Invoice
/*
CREATED BY: JORDAN GODWIN
CREATE DATE: 05/12/2023
DESCRIPTION: AGGREGATE FUNCTIONS \ WHAT ARE OUR ALL TIME GLOBAL SALES
*/
SELECT
	SUM(TOTAL) AS 'Total Sales'

FROM
	Invoice

