/*
CREATED BY: JORDAN GODWIN
CREATE DATE: 05/10/2023
DESCRIPTION: THIS QUERY DISPLAYS ALL CUSTOMERS' FIRST AND LAST NAMES AND EMAIL ADDRESSES
*/

SELECT
	FirstName AS [Customer First Name],
	LastName AS 'Customer Last Name',
	Email AS EMAIL 

FROM
	Customer
ORDER BY
	FirstName ASC,
	LastName DESC
LIMIT 10